spring.application.name=Pet-care
server.port=8081


spring.datasource.url=jdbc:mysql://localhost:3306/petcare
spring.datasource.username=root
spring.datasource.password=abdalah

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


logging.level.org.hibernate=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE






